name: build-dawn-msys2
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-python
            mingw-w64-ucrt-x86_64-cmake
      - name: Clone and Fetch Dependencies
        shell: pwsh
        run: |
          git clone https://dawn.googlesource.com/dawn
          cd dawn
          python tools/fetch_dawn_dependencies.py
      - name: Cmake
        shell: msys2 {0}
        run: |
          cd dawn
          mkdir -p out/Release
          cmake -S . -B out/Release -G Ninja -DDAWN_ENABLE_D3D12=OFF -DDAWN_ENABLE_D3D11=OFF -DDAWN_ENABLE_VULKAN=ON -DDAWN_USE_GLFW=OFF -DDAWN_BUILD_SAMPLES=OFF -DDAWN_ENABLE_NULL=OFF -DDAWN_USE_WINDOWS_UI=OFF -DTINT_BUILD_HLSL_WRITER=OFF -DDAWN_ENABLE_INSTALL=ON -DCMAKE_BUILD_TYPE=Release
      - name: Build
        shell: msys2 {0}
        run: |
          cd dawn
          sed -i '37a #include <share.h>\n#include <sys/stat.h>' ./src/tint/utils/file/tmpfile_windows.cc
          sed -n '35,40p' ./src/tint/utils/file/tmpfile_windows.cc
          cd out/Release
          ninja
      - name: Install
        shell: msys2 {0}
        run: |
          cd dawn
          cmake --install out/Release --prefix dawn-x86-64-windows-gnu-release
          tar -czf dawn-x86-64-windows-gnu-release.tar.gz dawn-x86-64-windows-gnu-release
      - name: Release
        uses: softprops/action-gh-release@v2.6.1
        with:
          files: |
            dawn/dawn-x86-64-windows-gnu-release.tar.gz
